spring:
  application:
    name: pantry-pos
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_pantry?serverTimezone=UTC
    username: root
    password:
